blank_issues_enabled: false
contact_links:
  - name: ğŸ“– ä½¿ç”¨è¯´æ˜ & å¸¸è§é—®é¢˜ï¼ˆFAQï¼‰
    url: https://github.com/Xposed-Modules-Repo/me.build/issues
    about: è¯·åœ¨æäº¤é—®é¢˜å‰å…ˆæŸ¥çœ‹æ–‡æ¡£æ˜¯å¦å·²æœ‰ç­”æ¡ˆ
